version: "3"
services:
  redis:
    image: redis:5
    volumes:
      - redis:/data
  custom-url-shortener-backend:
    build:
      context: ./custom-url-shortener-backend
      dockerfile: ../dockerfiles/Dockerfile.custom-url-shortener-backend
    ports:
      - 5000:5000
    depends_on:
      - redis
  custom-url-shortener-frontend:
    build:
      context: ./custom-url-shortener-frontend
      dockerfile: ../dockerfiles/Dockerfile.custom-url-shortener-frontend
    ports:
      - 3000:3000
    depends_on:
      - custom-url-shortener-backend

volumes:
  redis: